// <auto-generated />
using System;
using Directum360Feedback.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Directum360Feedback.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedOption")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 12, 13, 9, 51, 928, DateTimeKind.Utc).AddTicks(755),
                            Email = "ivanov@example.com",
                            FullName = "Иванов Иван Иванович"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 12, 13, 9, 51, 928, DateTimeKind.Utc).AddTicks(1698),
                            Email = "petrov@example.com",
                            FullName = "Петров Пётр Петрович"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 12, 13, 9, 51, 928, DateTimeKind.Utc).AddTicks(1701),
                            Email = "ivanova@example.com",
                            FullName = "Иванова Мария Ивановна"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 12, 13, 9, 51, 928, DateTimeKind.Utc).AddTicks(1703),
                            Email = "alexsandrovna@example.com",
                            FullName = "Александрова Александра Александровна"
                        });
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.QuestionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QuestionTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 12, 13, 9, 51, 928, DateTimeKind.Utc).AddTicks(9554),
                            Name = "Общая производительность команды",
                            Options = "[\"Отлично\",\"Хорошо\",\"Средне\",\"Плохо\",\"Ужасно\"]",
                            Text = "Как вы оцениваете общую производительность команды?",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 12, 13, 9, 51, 929, DateTimeKind.Utc).AddTicks(602),
                            Name = "Обратная связь",
                            Text = "Пожалуйста, оставьте дополнительные комментарии.",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.RespondentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RespondentTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Самооценка + руководитель + два коллеги",
                            Name = "Классическая 360"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Горизонтальная оценка без руководителя",
                            Name = "Только коллеги"
                        });
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.RespondentTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TemplateId");

                    b.ToTable("RespondentTemplateItems");

                    b.HasData(
                        new { Id = 1, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Role = 0, TemplateId = 1 },
                        new { Id = 2, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), EmployeeId = 1, Role = 1, TemplateId = 1 },
                        new { Id = 3, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), EmployeeId = 2, Role = 2, TemplateId = 1 },
                        new { Id = 4, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), EmployeeId = 3, Role = 2, TemplateId = 1 },
                        new { Id = 5, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), EmployeeId = 2, Role = 2, TemplateId = 2 },
                        new { Id = 6, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), EmployeeId = 3, Role = 2, TemplateId = 2 },
                        new { Id = 7, CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), EmployeeId = 4, Role = 2, TemplateId = 2 });
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.SurveyAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvaluatorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InviteSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurveyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("SurveyId");

                    b.HasIndex("TargetId");

                    b.ToTable("SurveyAssignments");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurveyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Directum360Feedback.Domain.Entities.SurveyAssignment", "Assignment")
                        .WithMany("Answers")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Directum360Feedback.Domain.Entities.SurveyQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.RespondentTemplateItem", b =>
                {
                    b.HasOne("Directum360Feedback.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Directum360Feedback.Domain.Entities.RespondentTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.Survey", b =>
                {
                    b.HasOne("Directum360Feedback.Domain.Entities.Employee", "Author")
                        .WithMany("AuthoredSurveys")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.SurveyAssignment", b =>
                {
                    b.HasOne("Directum360Feedback.Domain.Entities.Employee", "Evaluator")
                        .WithMany("AssignmentsAsEvaluator")
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Directum360Feedback.Domain.Entities.Survey", "Survey")
                        .WithMany("Assignments")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Directum360Feedback.Domain.Entities.Employee", "Target")
                        .WithMany("AssignmentsAsTarget")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluator");

                    b.Navigation("Survey");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("Directum360Feedback.Domain.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AssignmentsAsEvaluator");

                    b.Navigation("AssignmentsAsTarget");

                    b.Navigation("AuthoredSurveys");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.RespondentTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.Survey", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.SurveyAssignment", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Directum360Feedback.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
